version: "2.6"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - ./app/node_modules

  react:
    build: ./myblog
    container_name: react_c
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./myblog:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
